// Constants and functions used by both background.js and content_script.js

const DEBUG = true;
const DISPLAY_DEBUG_TIME = false;

const LIMIT_DELTA_TIME = 3; // In Seconds

const Actions = {
  PLAY: 'play',
  PAUSE: 'pause',
  READY: 'ready',
  ENDED: 'ended',
  TIMEUPDATE: 'timeupdate',
}

const States = {
  PLAYING: 'playing',
  PAUSED: 'paused',
}

const Site = {
  FUNIMATION: 'funimation',
  CRUNCHYROLL: 'crunchyroll',
  WAKANIM: 'wakanim',
}

// For messages generated by background.js capturing actions from the server.
const BackgroundMessageTypes = {
  REMOTE_UPDATE: 'remote_update',
  ROOM_CONNECTION: 'room_connection',
  REMOTE_CHAT: 'remote_chat',
  ROOM_DISCONNECT: 'room_disconnect',
  IS_FIRST: 'is_first',
}

// For messages generated by content_script.js capturing actions on the webpage.
const WebpageMessageTypes = {
  LOCAL_UPDATE: 'local_update',
  ROOM_CONNECTION: 'room_connection',
  CONNECTION: 'connection',
  LOCAL_CHAT: 'local_chat',
  ROOM_ID: 'room_id',
  RESYNC: 'resync',
}

function log() {
  const args = DISPLAY_DEBUG_TIME ? [(new Date()).toJSON()] : [];
  args.push(...arguments);
  return DEBUG && console.log(...args);
}

function getBackendUrl() {
  return new Promise(callback => {
    chrome.storage.sync.get({ backendUrl: "" }, function (data) {
      callback(data.backendUrl);
    });
  });
}

function getDefaultRoomId() {
  return new Promise(callback => {
    chrome.storage.sync.get({ defaultRoomId: "" }, function (data) {
      callback(data.defaultRoomId);
    });
  });
}

function getDefaultNick() {
  return new Promise(callback => {
    chrome.storage.sync.get({ defaultNick: "" }, function (data) {
      callback(data.defaultNick);
    });
  });
}

function setHasShownReleaseNotes(hasShown) {
  chrome.storage.sync.set({ hasShownReleaseNotes: hasShown });
}

function getHasShownReleaseNotes() {
  return new Promise(callback => {
    chrome.storage.sync.get({ hasShownReleaseNotes: false }, function (data) {
      callback(data.hasShownReleaseNotes);
    });
  });
}
